name: powermoniter-main

services:
  web:
    build: .
    hostname: powermoniter-web-main
    networks:
      edge:
        aliases:
          - powermoniter-main-web
    dns:
      - 8.8.8.8
      - 1.1.1.1
    expose:
      - "9000"    # 只在 Docker 网络内部暴露
    volumes:
      - .:/app
      - ./staticfiles:/app/staticfiles
      - ./media:/app/media
      - ./logs:/app/logs
    environment:
      - DEBUG=False
      - ALLOWED_HOSTS=localhost,127.0.0.1,0.0.0.0,81.68.79.234,47.237.84.36
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "3"

networks:  # docker network create edge
  edge:
    external: true