services:
  caddy:
    image: caddy
    ports: ["80:80","443:443", "8000:8000"]
    networks: ["edge"]
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile:ro
      - caddy-data:/data
      - caddy-config:/config
      - /root/powermoniter/staticfiles:/srv/static:ro
      - /root/powermoniter/media:/srv/media:ro
networks:
  edge:
    external: true
volumes:
  caddy-data:
  caddy-config: